- .editorconfig
- .gitignore
- CONTRIBUTING.md
- Dockerfile
- PULL_REQUEST_TEMPLATE.md
- README.md
- descriptors/DeploymentDescriptor-template.json
- descriptors/ModuleDescriptor-template.json
- lombok.config
- pom.xml
- src/main/java/org/folio/template/FolioSpringTemplateApplication.java
- src/main/resources/application.yml
- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/initial_schema.xml
- src/main/resources/swagger.api/examples/error.sample
- src/main/resources/swagger.api/examples/errors.sample
- src/main/resources/swagger.api/schemas/error.json
- src/main/resources/swagger.api/schemas/errors.json
- src/main/resources/swagger.api/schemas/metadata.json
- src/main/resources/swagger.api/schemas/parameter.json
- src/main/resources/swagger.api/schemas/parameters.json
- src/test/java/org/folio/template/FolioSpringTemplateApplicationTest.java
- src/test/java/org/folio/template/context/PostgresTestContainersBeanFactoryPostProcessor.java
- src/test/resources/application-test.yml
[MODREQMED-1](https://issues.folio.org/browse/MODREQMED-1)
> MODREQMED-1: Set up initial project structure

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- src/main/resources/swagger.api/requests-mediated.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
> FOLIO-3678 MODREQMED-4 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- PERSONAL_DATA_DISCLOSURE.md
- README.md
Add PERSONAL_DATA_DISCLOSURE.md form
Also, add a link to the issue tracker
Doc: https://dev.folio.org/guidelines/create-new-repo
JIRA ticket: https://issues.folio.org/browse/MODREQMED-5
> MODREQMED-5 Add PD disclosure form

- Dockerfile
Update packages in Dockerfile
[MODREQMED-7](https://folio-org.atlassian.net/browse/MODREQMED-7)
> MODREQMED-7 Update packages in Dockerfile

- src/main/java/org/folio/mr/service/impl/MediatedRequestsServiceImpl.java
- src/test/java/org/folio/mr/api/MediatedRequestsApiTest.java
MODREQMED-9 - changes that were not included in the original PR
> MODREQMED-9 Refactor tests

- src/main/java/org/folio/mr/controller/MediatedRequestsController.java
- src/main/resources/swagger.api/requests-mediated.yaml
- src/main/resources/swagger.api/schemas/confirmItemArrivalRequest.yaml
- src/test/java/org/folio/mr/controller/MediatedRequestsControllerTest.java
https://folio-org.atlassian.net/browse/MODREQMED-14
Add required endpoint
> MODREQMED-14: Create skeleton for a new endpoint - confirm item arrival

- src/main/java/org/folio/mr/controller/MediatedRequestActionsController.java
- src/main/java/org/folio/mr/repository/MediatedRequestsRepository.java
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/resources/swagger.api/examples/sendItemInTransitResponse.json
- src/main/resources/swagger.api/requests-mediated.yaml
- src/main/resources/swagger.api/schemas/sendItemInTransitResponse.yaml
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/controller/MediatedRequestActionsControllerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
https://folio-org.atlassian.net/browse/MODREQMED-22
Similar approach sued as for MODREQMED-21
> MODREQMED-22: Send item in transit by barcode - implementation

- src/main/java/org/folio/mr/controller/MediatedRequestActionsController.java
- src/main/java/org/folio/mr/domain/entity/MediatedRequestWorkflowLog.java
- src/main/java/org/folio/mr/repository/MediatedRequestWorkflowLogRepository.java
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/resources/db/changelog/changelog-1.0.0.xml
- src/main/resources/db/changelog/changes/v1.0.0/2024-08-30-create-mediated_request_workflow_log-table.xml
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/controller/MediatedRequestActionsControllerTest.java
- src/test/java/org/folio/mr/util/TestEntityBuilder.java
[MODREQMED-25](https://folio-org.atlassian.net/browse/MODREQMED-25)
Create a table for storing mediated request step historyю
Create xml migration script schema.
> MODREQMED-25 Create a table for storing mediated request step history

- descriptors/ModuleDescriptor-template.json
MODREQMED-23
Add inventory storage permissions
> MODREQMED-23 Add inventory storage permissions

- descriptors/ModuleDescriptor-template.json
Resolves: [MODREQMED-23](https://folio-org.atlassian.net/browse/MODREQMED-23)
> [MODREQMED-23] Add missed permissions

- src/main/java/org/folio/mr/domain/converter/CustomEnumExtractor.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestDetailsServiceImpl.java
- src/main/resources/db/changelog/changelog-1.0.0.xml
- src/main/resources/db/changelog/changes/v1.0.0/2024-09-18-make-some-mediated_request-columns-nullable.xml
- src/main/resources/swagger.api/schemas/mediatedRequest.yaml
- src/test/java/org/folio/mr/api/MediatedRequestsApiTest.java
https://folio-org.atlassian.net/browse/MODREQMED-28
Change schema, alter columns in the DB, fix custom enum parser to allow null values
> MODREQMED-28 Make type and fulfillment preference not required

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/mr/controller/ApiExceptionHandler.java
- src/main/java/org/folio/mr/controller/MediatedRequestActionsController.java
- src/main/java/org/folio/mr/exception/ExceptionFactory.java
- src/main/java/org/folio/mr/exception/MetadataUpdateException.java
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/MetadataServiceImpl.java
- src/main/resources/swagger.api/requests-mediated.yaml
- src/test/java/org/folio/mr/controller/MediatedRequestActionsControllerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
- src/test/java/org/folio/mr/service/MetadataServiceTest.java
https://folio-org.atlassian.net/browse/MODREQMED-26
Implement corresponding endpoint.
> MODREQMED-26: Decline mediated request - new endpoint

- descriptors/ModuleDescriptor-template.json
[MODREQMED-29](https://folio-org.atlassian.net/browse/MODREQMED-29)
> MODREQMED-29: Add support for interface instance-storage 11.0

- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
https://folio-org.atlassian.net/browse/MODREQMED-26
> MODREQMED-26 Fix declined request status field

- pom.xml
Upgrade to folio-spring-support 8.2.1 and Spring Boot 3.3.4
[MODREQMED-8](https://folio-org.atlassian.net/browse/MODREQMED-8)
> MODREQMED-8: Upgrade to folio-spring-support 8.2.1 and Spring Boot 3.3.4

- descriptors/ModuleDescriptor-template.json
[MODREQMED-47](https://folio-org.atlassian.net/browse/MODREQMED-47)
> MODREQMED-47 Add permission user-tenants.collection.get

- descriptors/ModuleDescriptor-template.json
Resolves: [MODREQMED-52](https://folio-org.atlassian.net/browse/MODREQMED-52)
> MODREQMED-52 Add system user section to the module descriptor

- descriptors/ModuleDescriptor-template.json
MODREQMED-48 Add system user permissions
> MODREQMED-48 Add system user permissions

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/mr/client/CirculationClient.java
- src/main/java/org/folio/mr/client/UserClient.java
- src/main/java/org/folio/mr/domain/dto/UserType.java
- src/main/java/org/folio/mr/domain/entity/FakePatronLink.java
- src/main/java/org/folio/mr/repository/FakePatronLinkRepository.java
- src/main/java/org/folio/mr/service/CirculationRequestService.java
- src/main/java/org/folio/mr/service/ConsortiumService.java
- src/main/java/org/folio/mr/service/UserService.java
- src/main/java/org/folio/mr/service/impl/CirculationRequestServiceImpl.java
- src/main/java/org/folio/mr/service/impl/ConsortiumServiceImpl.java
- src/main/java/org/folio/mr/service/impl/EcsRequestServiceImpl.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/UserServiceImpl.java
- src/main/resources/db/changelog/changelog-1.0.0.xml
- src/main/resources/db/changelog/changes/v1.0.0/2024-11-21-create_fake_patron_link-table.xml
- src/main/resources/permissions/mod-requests-mediated.csv
- src/main/resources/swagger.api/schemas/circulation/override-blocks.json
- src/main/resources/swagger.api/schemas/circulation/request-search-index.json
- src/main/resources/swagger.api/schemas/circulation/request.json
- src/main/resources/swagger.api/schemas/circulation/tags.json
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
Resolves: [MODREQMED-61](https://folio-org.atlassian.net/browse/MODREQMED-61)
> MODREQMED-61 Release 1.0.2

- descriptors/ModuleDescriptor-template.json
[MODREQMED-64](https://folio-org.atlassian.net/browse/MODREQMED-64)
> MODREQMED-64: Remove redundant permissions

- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/RequestEventHandler.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
https://folio-org.atlassian.net/browse/MODREQMED-65
React on request status change and update mediated request status accordingly.
> MODREQMED-65: Add status change in Mediated request workflow

- descriptors/ModuleDescriptor-template.json
[MODREQMED-68](https://folio-org.atlassian.net/browse/MODREQMED-68)
> MODREQMED-68: Add missing required interfaces

- pom.xml
Resolves: [MODREQMED-73](https://folio-org.atlassian.net/browse/MODREQMED-73)
> MODREQMED-73 Spring Boot 3.3.7, folio-spring 8.2.2 fixing vulns

- NEWS.md
- pom.xml
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/RequestEventHandler.java
- src/test/java/org/folio/mr/controller/KafkaEventListenerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
Resolves: [MODREQMED-75](https://folio-org.atlassian.net/browse/MODREQMED-75)
> MODREQMED-75 Release 1.0.4

- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
> MODREQMED-67 Routing Mediated requests pt1

- NEWS.md
- pom.xml
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
- src/test/java/org/folio/mr/util/TestEntityBuilder.java
Resolves: [MODREQMED-77](https://folio-org.atlassian.net/browse/MODREQMED-77)
> MODREQMED-77 Release 1.0.5

- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestDetailsServiceImpl.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
[MODREQMED-82](https://folio-org.atlassian.net/browse/MODREQMED-82)
> MODREQMED-82: Update local request upon confirmation

- src/main/java/org/folio/mr/domain/MediatedRequestStatus.java
- src/main/java/org/folio/mr/domain/entity/MediatedRequestStep.java
- src/main/java/org/folio/mr/service/CirculationRequestService.java
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/CirculationRequestServiceImpl.java
- src/main/java/org/folio/mr/service/impl/EcsRequestServiceImpl.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/RequestEventHandler.java
- src/main/java/org/folio/mr/support/Constants.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/controller/KafkaEventListenerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
[MODREQMED-86](https://folio-org.atlassian.net/browse/MODREQMED-86)
> MODREQMED-86: Implementation and tests for spike MODREQMED-83

- NEWS.md
- pom.xml
- src/main/java/org/folio/mr/domain/MediatedRequestStatus.java
- src/main/java/org/folio/mr/domain/entity/MediatedRequestStep.java
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/CirculationRequestServiceImpl.java
- src/main/java/org/folio/mr/service/impl/EcsRequestServiceImpl.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/RequestEventHandler.java
- src/main/java/org/folio/mr/support/Constants.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/controller/KafkaEventListenerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
Resolves: [MODREQMED-88](https://folio-org.atlassian.net/browse/MODREQMED-88)
> MODREQMED-88 Release 1.0.7

- src/main/java/org/folio/mr/client/SearchClient.java
- src/main/java/org/folio/mr/service/SearchService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/RequestEventHandler.java
- src/main/java/org/folio/mr/service/impl/SearchServiceImpl.java
- src/test/java/org/folio/mr/api/BaseIT.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/controller/KafkaEventListenerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
- src/test/java/org/folio/mr/util/MockHelper.java
[MODREQMED-93](https://folio-org.atlassian.net/browse/MODREQMED-93)
> MODREQMED-93: Update item info in title-level mediated request

- pom.xml
- src/main/java/org/folio/mr/domain/entity/MediatedRequestEntity.java
- src/test/java/org/folio/mr/repository/MediatedRequestsRepositoryTest.java
[MODREQMED-17](https://folio-org.atlassian.net/browse/MODREQMED-17)
> MODREQMED-17 mediated requests search needs to be case insensitive

- NEWS.md
- pom.xml
- src/main/java/org/folio/mr/controller/MediatedRequestActionsController.java
- src/main/java/org/folio/mr/domain/MediatedRequestContext.java
- src/main/java/org/folio/mr/service/MediatedRequestActionsService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/StaffSlipContextService.java
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/controller/MediatedRequestActionsControllerTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
- src/test/java/org/folio/mr/service/StaffSlipContextServiceTest.java
- src/test/java/org/folio/mr/util/TestEntityBuilder.java
https://folio-org.atlassian.net/browse/MODREQMED-110
> Bugfix release 1.0.10

- NEWS.md
- pom.xml
- src/main/java/org/folio/mr/service/impl/RequestEventHandler.java
- src/test/java/org/folio/mr/controller/KafkaEventListenerTest.java
Resolves: [MODREQMED-117](https://folio-org.atlassian.net/browse/MODREQMED-117)
> MODREQMED-117 Release 1.0.12

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/mr/client/DeclareLostCirculationClient.java
- src/main/java/org/folio/mr/client/DeclareLostTlrClient.java
- src/main/java/org/folio/mr/client/LoanClient.java
- src/main/java/org/folio/mr/controller/MediatedRequestLoansController.java
- src/main/java/org/folio/mr/repository/MediatedRequestsRepository.java
- src/main/java/org/folio/mr/service/DeclareLostService.java
- src/main/java/org/folio/mr/service/impl/DeclareLostServiceImpl.java
- src/main/resources/permissions/mod-requests-mediated.csv
- src/main/resources/swagger.api/requests-mediated.yaml
- src/main/resources/swagger.api/schemas/circulation-storage/loan.yaml
- src/main/resources/swagger.api/schemas/circulation/declareLostCirculationRequest.yaml
- src/main/resources/swagger.api/schemas/circulation/declareLostTlrRequest.yaml
- src/test/java/org/folio/mr/api/DeclareLostApiTest.java
- src/test/java/org/folio/mr/util/MockHelper.java
[MODREQMED-134](https://folio-org.atlassian.net/browse/MODREQMED-134)
> MODREQMED-134 Declare lost API for mediated requests

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/mr/client/DeclareLostCirculationClient.java
- src/main/java/org/folio/mr/client/DeclareLostTlrClient.java
- src/main/java/org/folio/mr/client/LoanClient.java
- src/main/java/org/folio/mr/controller/MediatedRequestLoansController.java
- src/main/java/org/folio/mr/repository/MediatedRequestsRepository.java
- src/main/java/org/folio/mr/service/DeclareLostService.java
- src/main/java/org/folio/mr/service/impl/DeclareLostServiceImpl.java
- src/main/resources/permissions/mod-requests-mediated.csv
- src/main/resources/swagger.api/requests-mediated.yaml
- src/main/resources/swagger.api/schemas/circulation-storage/loan.yaml
- src/main/resources/swagger.api/schemas/circulation/declareLostCirculationRequest.yaml
- src/main/resources/swagger.api/schemas/circulation/declareLostTlrRequest.yaml
- src/test/java/org/folio/mr/api/DeclareLostApiTest.java
- src/test/java/org/folio/mr/util/MockHelper.java
Resolves: [MODREQMED-145](https://folio-org.atlassian.net/browse/MODREQMED-145)
> MODREQMED-145 Release 1.2.4

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/mr/controller/ApiExceptionHandler.java
- src/main/java/org/folio/mr/domain/type/ErrorCode.java
- src/main/java/org/folio/mr/exception/ValidationException.java
- src/main/java/org/folio/mr/service/UserService.java
- src/main/java/org/folio/mr/service/ValidatorService.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestActionsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/MediatedRequestsServiceImpl.java
- src/main/java/org/folio/mr/service/impl/UserServiceImpl.java
- src/main/java/org/folio/mr/service/impl/ValidatorServiceImpl.java
- src/main/resources/swagger.api/requests-mediated.yaml
- src/test/java/org/folio/mr/api/MediatedRequestActionsApiTest.java
- src/test/java/org/folio/mr/api/MediatedRequestsApiTest.java
- src/test/java/org/folio/mr/service/MediatedRequestActionsServiceTest.java
- src/test/java/org/folio/mr/service/UserServiceTest.java
- src/test/java/org/folio/mr/service/ValidatorServiceImplTests.java
Resolves: [MODREQMED-153](https://folio-org.atlassian.net/browse/MODREQMED-153)
> MODREQMED-153 Release 1.0.19

- NEWS.md
- pom.xml
- src/main/java/org/folio/mr/listener/kafka/KafkaEventListener.java
- src/test/java/org/folio/mr/controller/KafkaEventListenerTest.java
https://folio-org.atlassian.net/browse/MODREQMED-183
> Bugfix release 1.2.8
